#line 1 "lexer/lex.yy.c"

#line 3 "lexer/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 130
#define YY_END_OF_BUFFER 131
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[497] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  131,  129,
      127,  128,  129,  129,  129,  122,  123,  121,  129,  116,
      116,  124,  120,  102,  101,  103,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  126,   87,   82,   83,
       87,   85,   87,   91,   88,   89,   90,   97,   92,   93,
       97,   95,   97,  127,  108,  107,    0,  118,  117,    0,
      112,    0,  116,  115,  115,   99,   98,  100,  119,  119,
      119,  119,  119,  119,  119,  105,  119,  119,  119,   10,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  104,

        7,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   35,  106,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  126,  125,   82,    0,   86,   85,
        0,   84,   88,   92,    0,   96,   95,    0,   94,    0,
        0,    0,    0,  113,  115,  111,   18,   30,   34,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,   11,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   23,  119,  119,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,   36,   86,   96,    0,    0,  114,  119,
      119,  119,  119,    6,    2,  119,  119,  119,  119,   29,
        9,  119,  119,  119,   15,  119,   20,  119,   13,  119,
       43,  119,   44,  119,  119,   17,  119,  119,   51,   47,
      119,  119,  119,    4,  119,  119,   22,  119,   49,  119,
      119,  119,  119,  119,   62,   56,  119,   79,  119,  119,
       67,  119,  119,  119,   19,   37,    8,  119,  119,  119,
      119,   65,  119,  119,    0,    0,  119,   21,   48,  119,

      119,  119,  119,  119,  119,   69,   80,   39,  119,  119,
       26,  119,  119,  119,  119,  119,  119,  119,   52,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,   71,   66,  119,  119,  119,  119,  119,
      119,  119,   12,   50,    0,   61,  119,  119,    3,   53,
      119,   33,  119,   76,  119,   28,   78,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   16,  119,  119,  119,  119,   24,   25,  119,
      119,  119,  119,  119,    0,  119,   54,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,    1,  119,

      119,  119,   60,   68,   64,   63,  119,  119,  119,   75,
      119,   57,  119,  119,  119,  119,  119,  119,    5,  119,
      119,   32,   38,  119,  119,   59,   58,  119,  119,  110,
      119,  119,  119,   31,   45,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  109,  119,  119,  119,  119,
       27,  119,  119,   55,  119,  119,  119,  119,  119,  119,
       70,  119,  119,  119,  119,  119,   77,  119,   40,   46,
      119,  119,  119,   41,   72,  119,  119,  119,   74,  119,
      119,  119,   73,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   81,   14,   42,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    5,    6,    7,
        8,    1,    1,    9,   10,   11,    1,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   14,   15,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       29,   36,   37,   38,   39,   40,   41,   42,   43,   29,
        1,   44,    1,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   29,   55,   56,   57,   58,
       59,   60,   29,   61,   62,   63,   64,   65,   66,   67,
       68,   29,   69,    1,   70,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    4,    4,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1
    } ;

static const flex_int16_t yy_base[515] =
    {   0,
        0,    0,   70,  140,   88,   90,  210,  280,  705, 1182,
      701, 1182,   82,   85,  116, 1182, 1182, 1182,   88,   96,
      104, 1182, 1182,   93, 1182,  683,  141,    0,  141,  217,
      277,  142,   69,  219,   77,  214,  281,  145,  133,  317,
      157,  362,  278,  138,  213,  143,  630, 1182,  612, 1182,
      111,    0,  528, 1182,  560, 1182, 1182, 1182,  521, 1182,
      120,    0,  436,  503,  123,  222,  123, 1182,  456,  331,
      244,  248,  346,    0,  417, 1182, 1182, 1182,    0,  141,
      159,  182,  214,  219,  288,    0,  212,  291,  315,    0,
      211,  274,  318,  343,  333,  327,  335,  332,  331,    0,

        0,  333,  341,  341,  351,  351,  358,  352,  371,  367,
      373,  395,    0,    0,  415,  390,  386,  400,  456,  394,
      419,  434,  454,  414,  433,  418,  436,  439,  463,  437,
      456,  457,  471,  453,  386, 1182,  449,  402,    0,    0,
      336, 1182,  403,  381,  508,    0,    0,  301, 1182,  448,
      124,  523,  518,  526,    0,    0,    0,    0,    0,  479,
      488,  466,  483,  481,  513,  514,  526,  529,  524,  516,
      531,  319,  520,  524,  522,  539,  532,  532,  531,  528,
      544,  554,  554,  556,  568,  569,  557,  568,  573,  566,
      317,  568,    0,  568,  581,  578,  578,  309,  585,  586,

      576,  589,  577,  577,  593,  598,  280,  587,  595,  596,
      600,  610,  607,  607,  608,  615,  625,  618,  626,  630,
      618,  627,  621,    0,    0,    0,  649,  705,  673,  638,
      629,  639,  642,    0,    0,  639,  636,  643,  645,    0,
        0,  644,  658,  659,    0,  669,    0,  678,  273,  670,
        0,  669,    0,  670,  272,    0,  682,  685,    0,  267,
      685,  676,  679,    0,  685,  699,    0,  710,    0,  705,
      718,  723,  711,  711,    0,    0,  751,    0,  725,  712,
        0,  724,  720,  724,    0,    0,    0,  728,  726,  738,
      731,    0,  741,  753,  801,  550,  748,    0,  264,  762,

      762,  769,  747,  770,  772,    0,    0,    0,  771,  778,
        0,  784,  781,  792,  793,  798,  805,  807,    0,  803,
      812,  262,  807,  816,  798,  802,  803,  806,  821,  821,
      821,  827,  844,    0,    0,  843,  836,  850,  834,  849,
      851,  854,    0,    0,  891,    0,  840,  844,  259,    0,
      850,    0,  858,    0,  869,    0,    0,  865,  878,  872,
      882,  892,  886,  885,  893,  904,  892,  892,  906,  904,
      908,  909,    0,  898,  908,  912,  906,    0,    0,  929,
      917,  936,  926,  943,  883,  936,    0,  940,  942,  945,
      936,  936,  930,  944,  939,  943,  941,  936,    0,  961,

      946,  946,    0,    0,    0,    0,  949,  951,  973,    0,
      961,    0,  966,  258,  968,  973,  983,  990,    0,  990,
      984,    0,    0,  983,  995,    0,    0,  997,  984,    0,
      992,  989,  987,    0,    0, 1001, 1004, 1006, 1008,  996,
     1002, 1016, 1003, 1009, 1022,    0, 1030, 1017, 1028, 1022,
        0, 1029, 1034,    0, 1034, 1028,  201, 1026, 1045, 1032,
        0, 1038, 1040, 1033, 1053, 1051,    0, 1040,    0,    0,
     1046, 1052, 1065,    0,    0, 1056, 1065, 1070,    0, 1062,
     1075, 1070,    0, 1076,  150, 1084, 1077, 1078, 1081, 1083,
     1084, 1077,    0,    0,    0, 1182, 1143, 1147, 1151, 1155,

     1157,  185, 1161,  182,  181, 1165,  179,  167, 1169, 1173,
      117,  116,  109, 1177
    } ;

static const flex_int16_t yy_def[515] =
    {   0,
      496,    1,  497,  497,  498,  498,  499,  499,  496,  496,
      496,  496,  496,  496,  500,  496,  496,  496,  496,  501,
      501,  496,  496,  496,  496,  496,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  503,  496,  496,  496,
      504,  505,  506,  496,  496,  496,  496,  496,  496,  496,
      507,  508,  509,  496,  496,  496,  500,  496,  496,  510,
      496,  496,  501,  511,  511,  496,  496,  496,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,

      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  503,  496,  496,  504,  512,  505,
      506,  496,  496,  496,  507,  513,  508,  509,  496,  514,
      510,  500,  496,  496,  511,   75,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,

      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  512,  513,  496,  152,  496,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  514,  500,  502,  502,  502,  502,

      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  295,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  514,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,

      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,    0,  496,  496,  496,  496,

      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496
    } ;

static const flex_int16_t yy_nxt[1253] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       10,   20,   21,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   28,   34,   28,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   28,
       45,   46,   28,   10,   28,   27,   28,   29,   30,   31,
       32,   33,   28,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   28,   45,   46,   28,   47,   10,
       48,   49,   50,   48,   48,   48,   48,   48,   48,   48,
       48,   51,   51,   51,   48,   48,   48,   48,   48,   55,
       56,   55,   56,   65,   65,   65,   66,   66,   66,   71,

       71,   71,   99,   57,  103,   57,   72,   73,   73,   73,
       76,   77,  226,   48,   72,   73,   73,   73,   68,  225,
      155,   69,  138,  138,  138,   68,   68,   99,   69,  496,
      103,  145,  145,  145,   65,   65,   65,   75,   53,   48,
       48,   49,   50,   48,   48,   48,   48,   48,   48,   48,
       48,   51,   51,   51,   48,   48,   48,   48,   48,   70,
       83,   80,   75,   81,  110,   96,   70,  112,  113,   97,
      147,   84,  130,   82,   85,   98,  134,  157,  111,  118,
      119,  158,  146,   48,  140,  139,   83,   80,   79,   81,
      110,   96,  112,  113,  488,   97,   84,  130,   82,   85,

       98,  134,  157,  111,  159,  118,  119,  158,   53,   48,
       58,   59,   60,   58,   58,   58,   58,   58,   58,   58,
       58,   61,   61,   61,   58,   58,   58,   58,   58,   86,
      159,  100,  131,   66,   66,   66,   87,  104,  170,  132,
       88,  105,  161,  101,   89,  468,  160,  106,  133,  165,
       90,  102,  162,   58,  153,   71,   71,   71,  131,  154,
      154,  154,   87,  104,  170,  132,   88,  105,  161,  101,
       89,  160,  106,  133,  165,   90,  102,  162,   63,   58,
       58,   59,   60,   58,   58,   58,   58,   58,   58,   58,
       58,   61,   61,   61,   58,   58,   58,   58,   58,   91,

      107,  126,  436,  388,  127,  128,  366,   92,  347,   93,
      171,  317,   94,  129,  108,  166,  314,  310,   95,  109,
      163,  167,  164,   58,  277,   91,  107,  126,  114,  114,
      127,  128,   92,   68,   93,  171,  150,   94,  129,  108,
      172,  166,   67,   95,  109,  163,  167,  164,   63,   58,
      115,  168,  116,  268,  169,  117,   72,   73,   73,   73,
      175,  261,  173,  242,  176,  177,  172,  178,  179,  180,
      149,  181,  152,  182,   67,  115,  168,  116,  174,  169,
      117,  120,  144,  183,  184,  121,  175,  185,  173,  176,
      177,  186,  178,  179,  180,  122,  181,  152,  182,  123,

      124,  187,  125,  174,  143,  142,  188,  120,  183,  184,
      189,  121,  185,  138,  138,  138,  186,  194,  190,  198,
      122,  196,  197,  195,  123,  124,  187,  125,  156,  156,
      156,  188,  191,  205,  213,  189,  156,  156,  156,  156,
      156,  156,  192,  194,  190,  198,  196,  197,  195,  193,
      137,  206,  214,   69,  215,  136,  207,  191,  205,  216,
      213,  150,  156,  156,  156,  156,  156,  156,  192,  208,
      217,  220,  209,  210,  193,  199,  206,  200,  214,  215,
      201,  207,  218,  221,  222,  216,  202,  211,  224,  212,
      219,  227,  203,  204,  208,  217,  220,  209,  223,  210,

      230,  199,  232,  200,   64,  149,  201,  231,  218,  221,
      222,  202,  211,  224,  212,  233,  219,  203,  204,  145,
      145,  145,  144,  234,  223,   68,  230,  232,   69,  229,
      229,  229,  235,  231,  228,  228,  228,  154,  154,  154,
      233,  236,  228,  228,  228,  228,  228,  228,  234,  237,
      238,  239,   68,  240,  241,   69,  243,  244,  235,  245,
      246,  143,  247,  248,  249,  250,   70,  236,  228,  228,
      228,  228,  228,  228,  251,  237,  238,  239,  240,  252,
      241,  243,  244,  253,  245,  254,  246,  247,  248,  249,
      250,  255,  256,   70,  257,  258,  259,  142,  260,  251,

      262,  263,  264,  266,  267,  252,  265,  269,  253,  270,
      254,  271,  272,  137,  273,  274,  275,  255,  256,  257,
      276,  258,  259,  260,  278,  262,  263,  279,  264,  266,
      267,  280,  265,  269,  281,  270,  271,  282,  272,  273,
      274,  285,  275,  283,  284,  286,  276,  287,  288,  278,
      289,  290,  279,  291,  150,  292,  280,  293,  294,  281,
      150,  297,  299,  282,  298,  300,  285,  304,  283,  284,
      286,  301,  287,  302,  288,  289,  303,  290,  305,  291,
      292,  306,  293,  294,  229,  229,  229,  297,  299,  298,
      295,  300,  150,  304,  307,  308,  301,  309,  302,  136,

       78,  303,   64,  305,  496,  311,  312,  306,  313,  315,
      316,  318,  496,  319,  320,  295,  296,  296,  296,  307,
      321,  308,  322,  309,  296,  296,  296,  296,  296,  296,
      311,  312,  325,  313,  323,  315,  316,  318,  319,  320,
      324,  326,  327,  496,  328,  321,  329,  334,  322,  335,
      296,  296,  296,  296,  296,  296,  336,  337,  325,  338,
      323,  339,  340,  341,  343,  324,  342,  326,  327,  328,
      330,  329,  331,  334,  335,  332,  344,  496,  346,  351,
      333,  336,  337,  348,  338,  349,  339,  340,  496,  341,
      343,  342,  350,  352,  496,  496,  330,  496,  331,  496,

      355,  332,  344,  346,  351,  333,   69,  353,  354,  348,
      356,  349,  345,  345,  345,  357,  358,  360,  350,  352,
      345,  345,  345,  345,  345,  345,  355,  359,  361,  363,
      364,  365,  353,  354,  367,  368,  356,  369,  370,  371,
      357,  372,  358,  360,  227,  362,  345,  345,  345,  345,
      345,  345,  359,  373,  361,  363,  364,  365,  374,  375,
      367,  368,  369,  370,  371,  376,  372,  377,  378,  380,
      362,  379,  381,  382,  383,  384,  496,  496,  373,  496,
      386,  387,  389,  374,  375,  496,  496,  496,   69,  496,
      376,  390,  391,  377,  378,  380,  379,  381,  392,  382,

      383,  384,  385,  385,  385,  386,  387,  389,  393,  394,
      385,  385,  385,  385,  385,  385,  390,  395,  391,  396,
      496,  397,  398,  392,  399,  400,  227,  401,  402,  403,
      404,  405,  406,  393,  394,  407,  385,  385,  385,  385,
      385,  385,  395,  408,  409,  396,  397,  398,  410,  399,
      411,  400,  401,  402,  412,  403,  404,  405,  406,  413,
      407,  414,  415,  416,  417,  418,  419,  423,  408,  409,
      420,  421,  422,  410,  424,  425,  411,  426,  427,  412,
      428,  496,  429,  430,  431,  413,  414,  432,  415,  416,
      417,  418,  419,  423,  433,  420,  421,  422,  434,  424,

      425,  435,  426,  427,  437,  438,  428,  429,  430,  431,
      439,  440,  432,  441,  496,  442,  443,  444,  445,  447,
      433,  446,  448,  434,  449,  450,  435,  451,  452,  437,
      438,  453,  496,  454,  455,  456,  439,  440,  457,  441,
      442,  443,  458,  444,  445,  447,  446,  448,  459,  449,
      460,  450,  461,  451,  452,  462,  466,  453,  454,  455,
      463,  456,  464,  457,  465,  467,  469,  458,  470,  496,
      471,  472,  473,  474,  459,  475,  460,  461,  476,  496,
      477,  462,  466,  478,  479,  463,  480,  464,  481,  465,
      467,  469,  482,  483,  470,  471,  472,  473,  474,  484,

      485,  475,  486,  487,  476,  477,  489,  496,  478,  479,
      490,  491,  480,  481,  492,  493,  494,  495,  482,  483,
      496,  496,  496,  496,  484,  496,  485,  486,  496,  487,
      496,  496,  489,  496,  496,  490,  491,  496,  496,  492,
      493,  494,  495,   52,   52,   52,   52,   54,   54,   54,
       54,   62,   62,   62,   62,   67,   67,   67,   67,   74,
       74,  135,  135,  135,  135,  141,  141,  141,  141,  148,
      148,  148,  148,  151,  151,  151,  151,  150,  496,  150,
      150,    9,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,

      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496
    } ;

static const flex_int16_t yy_chk[1253] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    5,
        5,    6,    6,   13,   13,   13,   14,   14,   14,   19,

       19,   19,   33,    5,   35,    6,   20,   20,   20,   20,
       24,   24,  513,    3,   21,   21,   21,   21,   15,  512,
      511,   15,   51,   51,   51,   67,  151,   33,   67,  151,
       35,   61,   61,   61,   65,   65,   65,   20,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,   15,
       29,   27,   20,   27,   38,   32,   67,   39,   39,   32,
      508,   29,   44,   27,   29,   32,   46,   80,   38,   41,
       41,   81,  507,    4,  505,  504,   29,   27,  502,   27,
       38,   32,   39,   39,  485,   32,   29,   44,   27,   29,

       32,   46,   80,   38,   82,   41,   41,   81,    4,    4,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,   30,
       82,   34,   45,   66,   66,   66,   30,   36,   91,   45,
       30,   36,   84,   34,   30,  457,   83,   36,   45,   87,
       30,   34,   84,    7,   71,   71,   71,   71,   45,   72,
       72,   72,   30,   36,   91,   45,   30,   36,   84,   34,
       30,   83,   36,   45,   87,   30,   34,   84,    7,    7,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,   31,

       37,   43,  414,  349,   43,   43,  322,   31,  299,   31,
       92,  260,   31,   43,   37,   88,  255,  249,   31,   37,
       85,   88,   85,    8,  207,   31,   37,   43,   40,   40,
       43,   43,   31,   70,   31,   92,   70,   31,   43,   37,
       93,   88,   70,   31,   37,   85,   88,   85,    8,    8,
       40,   89,   40,  198,   89,   40,   73,   73,   73,   73,
       95,  191,   94,  172,   96,   97,   93,   98,   99,  102,
      148,  103,   70,  104,   70,   40,   89,   40,   94,   89,
       40,   42,  144,  105,  106,   42,   95,  107,   94,   96,
       97,  108,   98,   99,  102,   42,  103,   70,  104,   42,

       42,  109,   42,   94,  143,  141,  110,   42,  105,  106,
      111,   42,  107,  138,  138,  138,  108,  116,  112,  118,
       42,  117,  117,  116,   42,   42,  109,   42,   75,   75,
       75,  110,  112,  120,  124,  111,   75,   75,   75,   75,
       75,   75,  115,  116,  112,  118,  117,  117,  116,  115,
      137,  121,  125,  150,  126,  135,  121,  112,  120,  127,
      124,   69,   75,   75,   75,   75,   75,   75,  115,  122,
      128,  130,  122,  123,  115,  119,  121,  119,  125,  126,
      119,  121,  129,  131,  132,  127,  119,  123,  134,  123,
      129,  150,  119,  119,  122,  128,  130,  122,  133,  123,

      160,  119,  162,  119,   64,   63,  119,  161,  129,  131,
      132,  119,  123,  134,  123,  163,  129,  119,  119,  145,
      145,  145,   59,  164,  133,  152,  160,  162,  152,  153,
      153,  153,  165,  161,  152,  152,  152,  154,  154,  154,
      163,  166,  152,  152,  152,  152,  152,  152,  164,  167,
      168,  169,  296,  170,  171,  296,  173,  174,  165,  175,
      176,   55,  177,  178,  179,  180,  152,  166,  152,  152,
      152,  152,  152,  152,  181,  167,  168,  169,  170,  182,
      171,  173,  174,  183,  175,  184,  176,  177,  178,  179,
      180,  185,  186,  296,  187,  188,  189,   53,  190,  181,

      192,  194,  195,  196,  197,  182,  195,  199,  183,  200,
      184,  201,  202,   49,  203,  204,  205,  185,  186,  187,
      206,  188,  189,  190,  208,  192,  194,  209,  195,  196,
      197,  210,  195,  199,  211,  200,  201,  212,  202,  203,
      204,  214,  205,  213,  213,  215,  206,  216,  217,  208,
      218,  219,  209,  220,  227,  221,  210,  222,  223,  211,
      227,  230,  232,  212,  231,  233,  214,  239,  213,  213,
      215,  236,  216,  237,  217,  218,  238,  219,  242,  220,
      221,  243,  222,  223,  229,  229,  229,  230,  232,  231,
      227,  233,  227,  239,  244,  246,  236,  248,  237,   47,

       26,  238,   11,  242,    9,  250,  252,  243,  254,  257,
      258,  261,    0,  262,  263,  227,  228,  228,  228,  244,
      265,  246,  266,  248,  228,  228,  228,  228,  228,  228,
      250,  252,  270,  254,  268,  257,  258,  261,  262,  263,
      268,  271,  272,    0,  273,  265,  274,  279,  266,  280,
      228,  228,  228,  228,  228,  228,  282,  283,  270,  284,
      268,  288,  289,  290,  293,  268,  291,  271,  272,  273,
      277,  274,  277,  279,  280,  277,  294,    0,  297,  303,
      277,  282,  283,  300,  284,  301,  288,  289,    0,  290,
      293,  291,  302,  304,    0,    0,  277,    0,  277,    0,

      310,  277,  294,  297,  303,  277,  295,  305,  309,  300,
      312,  301,  295,  295,  295,  313,  314,  316,  302,  304,
      295,  295,  295,  295,  295,  295,  310,  315,  317,  318,
      320,  321,  305,  309,  323,  324,  312,  325,  326,  327,
      313,  328,  314,  316,  295,  317,  295,  295,  295,  295,
      295,  295,  315,  329,  317,  318,  320,  321,  330,  331,
      323,  324,  325,  326,  327,  332,  328,  333,  336,  338,
      317,  337,  339,  340,  341,  342,    0,    0,  329,    0,
      347,  348,  351,  330,  331,    0,    0,    0,  385,    0,
      332,  353,  355,  333,  336,  338,  337,  339,  358,  340,

      341,  342,  345,  345,  345,  347,  348,  351,  359,  360,
      345,  345,  345,  345,  345,  345,  353,  361,  355,  362,
        0,  363,  364,  358,  365,  366,  385,  367,  368,  369,
      370,  371,  372,  359,  360,  374,  345,  345,  345,  345,
      345,  345,  361,  375,  376,  362,  363,  364,  377,  365,
      380,  366,  367,  368,  381,  369,  370,  371,  372,  382,
      374,  383,  384,  386,  388,  389,  390,  394,  375,  376,
      391,  392,  393,  377,  395,  396,  380,  397,  398,  381,
      400,    0,  401,  402,  407,  382,  383,  408,  384,  386,
      388,  389,  390,  394,  409,  391,  392,  393,  411,  395,

      396,  413,  397,  398,  415,  416,  400,  401,  402,  407,
      417,  418,  408,  420,    0,  421,  424,  425,  428,  431,
      409,  429,  432,  411,  433,  436,  413,  437,  438,  415,
      416,  439,    0,  440,  441,  442,  417,  418,  443,  420,
      421,  424,  444,  425,  428,  431,  429,  432,  445,  433,
      447,  436,  448,  437,  438,  449,  455,  439,  440,  441,
      450,  442,  452,  443,  453,  456,  458,  444,  459,    0,
      460,  462,  463,  464,  445,  465,  447,  448,  466,    0,
      468,  449,  455,  471,  472,  450,  473,  452,  476,  453,
      456,  458,  477,  478,  459,  460,  462,  463,  464,  480,

      481,  465,  482,  484,  466,  468,  486,    0,  471,  472,
      487,  488,  473,  476,  489,  490,  491,  492,  477,  478,
        0,    0,    0,    0,  480,    0,  481,  482,    0,  484,
        0,    0,  486,    0,    0,  487,  488,    0,    0,  489,
      490,  491,  492,  497,  497,  497,  497,  498,  498,  498,
      498,  499,  499,  499,  499,  500,  500,  500,  500,  501,
      501,  503,  503,  503,  503,  506,  506,  506,  506,  509,
      509,  509,  509,  510,  510,  510,  510,  514,    0,  514,
      514,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,

      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer/tbol.l"
/*
 * Copyright 2025-2026, Phillip Heller
 *
 * This file is part of Prodigy Reloaded.
 *
 * Prodigy Reloaded is free software: you can redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * Prodigy Reloaded is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Prodigy Reloaded. If not,
 * see <https://www.gnu.org/licenses/>.
 */
#line 18 "lexer/tbol.l"
/*
 * TBOL Compiler - Lexical Analyzer
 */

/* Suppress warnings in flex-generated code */
#ifdef __clang__
#pragma clang diagnostic ignored "-Wsign-compare"
#endif

#include <string.h>
#include <stdlib.h>
#include "tokens.h"
#include "preproc.h"
#include "preproc_event.h"
#include "../parser/yyltype.h"  /* Must come before tbol.tab.h for custom YYLTYPE */
#include "../parser/tbol.tab.h"
#include "../diag/diag.h"

/* Location tracking - exported for preproc.c */
static const char *current_filename = NULL;
int current_line = 1;
int current_column = 1;
static char line_buffer[4096];
static int line_buffer_pos = 0;

/* Filename string pool for YYLTYPE - prevents leaking on every token */
#define FILENAME_POOL_SIZE 32
static const char *filename_pool[FILENAME_POOL_SIZE];
static int filename_pool_count = 0;

/* Intern a filename string - returns pooled pointer or adds to pool */
static const char *intern_filename(const char *filename) {
    if (!filename) return NULL;

    /* Check if already in pool */
    for (int i = 0; i < filename_pool_count; i++) {
        if (strcmp(filename_pool[i], filename) == 0) {
            return filename_pool[i];
        }
    }

    /* Add to pool if room */
    if (filename_pool_count < FILENAME_POOL_SIZE) {
        filename_pool[filename_pool_count] = strdup(filename);
        return filename_pool[filename_pool_count++];
    }

    /* Pool full - just strdup (shouldn't happen with typical include depths) */
    return strdup(filename);
}

/* Clear filename pool - call at lexer reset/cleanup */
void lexer_clear_filename_pool(void) {
    for (int i = 0; i < filename_pool_count; i++) {
        free((void *)filename_pool[i]);
        filename_pool[i] = NULL;
    }
    filename_pool_count = 0;
}

#define UPDATE_LOC() do { \
    yylloc.first_line = yylloc.last_line = current_line; \
    yylloc.first_column = current_column; \
    yylloc.last_column = current_column + yyleng - 1; \
    yylloc.filename = intern_filename(current_filename); \
    current_column += yyleng; \
} while(0)

#define NEWLINE() do { \
    if (line_buffer_pos > 0) { \
        line_buffer[line_buffer_pos] = '\0'; \
        diag_set_source_line(current_filename, current_line, line_buffer); \
        line_buffer_pos = 0; \
    } \
    current_line++; \
    current_column = 1; \
} while(0)

#define SAVE_TEXT() do { \
    for (int i = 0; yytext[i] && i < (int)(sizeof(line_buffer) - line_buffer_pos - 1); i++) { \
        if (yytext[i] == '\n') break; \
        line_buffer[line_buffer_pos++] = yytext[i]; \
    } \
} while(0)

static char *strupper(char *s) {
    for (char *p = s; *p; p++) {
        if (*p >= 'a' && *p <= 'z') *p -= 32;
    }
    return s;
}

/* Track last processed string length (for embedded nulls) */
static int last_string_length = 0;

int lexer_get_last_string_length(void) {
    return last_string_length;
}

static char *process_string(const char *s) {
    size_t len = strlen(s);
    if (len < 2) {
        last_string_length = 0;
        return strdup("");
    }
    char *result = malloc(len - 1);
    if (!result) return NULL;
    char *dst = result;
    const char *src = s + 1;
    const char *end = s + len - 1;
    while (src < end) {
        if (*src == '\\' && src + 1 < end) {
            /* Backslash escape */
            src++;
            if (*src == '\'') {
                *dst++ = '\'';
            } else if (*src == '\\') {
                *dst++ = '\\';
            } else if (*src == 'x' && src + 2 < end) {
                /* Hex escape \xNN */
                char hex[3] = {src[1], src[2], '\0'};
                char *endp;
                long val = strtol(hex, &endp, 16);
                if (endp == hex + 2) {
                    *dst++ = (char)val;
                    src += 2;  /* Skip the two hex digits (x already skipped) */
                } else {
                    /* Invalid hex - keep as-is */
                    *dst++ = '\\';
                    *dst++ = *src;
                }
            } else if (*src == '0') {
                /* Null escape \0 */
                *dst++ = '\0';
            } else {
                /* Unknown escape - keep as-is */
                *dst++ = '\\';
                *dst++ = *src;
            }
            src++;
        } else {
            *dst++ = *src++;
        }
    }
    *dst = '\0';
    last_string_length = (int)(dst - result);
    return result;
}

void lexer_set_filename(const char *filename) {
    free((void *)current_filename);
    current_filename = filename ? strdup(filename) : NULL;
    current_line = 1;
    current_column = 1;
    line_buffer_pos = 0;
}

/* Set filename without resetting line/column - for COPY transparency */
void lexer_set_filename_only(const char *filename) {
    free((void *)current_filename);
    current_filename = filename ? strdup(filename) : NULL;
}

const char *lexer_get_filename(void) {
    return current_filename;
}

/* Buffer stack for COPY file handling - use flex's built-in stack */
#define MAX_INCLUDE_DEPTH 32
static FILE *file_stack[MAX_INCLUDE_DEPTH];
static int file_stack_ptr = 0;

/* Temporary storage for COPY filename while waiting for semicolon */
static char *copy_filename = NULL;

/* COPY keyword location (saved when COPY is seen, used when event is recorded) */
static int copy_start_line = 0;
static int copy_start_col = 0;

/* Forward declarations - defined in flex-generated code */
extern void yy_delete_buffer(YY_BUFFER_STATE b);
extern void yypop_buffer_state(void);

/* Full lexer cleanup - frees stacked flex buffers and resets state.
 * Must be called between successive parses to prevent buffer leaks.
 * Does NOT call yylex_destroy (which breaks subsequent yyrestart). */
void lexer_cleanup(void) {
    lexer_clear_filename_pool();
    free((void *)current_filename);
    current_filename = NULL;
    free(copy_filename);
    copy_filename = NULL;

    /* Pop any leftover COPY file buffers from the stack */
    while (file_stack_ptr > 0) {
        file_stack_ptr--;
        /* Close file handles left on the stack */
        if (file_stack[file_stack_ptr]) {
            fclose(file_stack[file_stack_ptr]);
            file_stack[file_stack_ptr] = NULL;
        }
        yypop_buffer_state();
    }
}

void lexer_push_buffer(FILE *fp) {
    if (file_stack_ptr >= MAX_INCLUDE_DEPTH) {
        /* Should not happen - preproc checks depth */
        return;
    }
    /* Save current file handle */
    file_stack[file_stack_ptr++] = yyin;

    /* Push current buffer and switch to new one */
    yypush_buffer_state(yy_create_buffer(fp, YY_BUF_SIZE));
    yyin = fp;
}

void lexer_pop_buffer(void) {
    if (file_stack_ptr <= 0) {
        return;
    }
    /* Close current file */
    if (yyin) {
        fclose(yyin);
    }

    /* Pop buffer (this deletes current and switches to previous) */
    yypop_buffer_state();

    /* Restore file handle */
    yyin = file_stack[--file_stack_ptr];
}

/*
 * Handle an identifier token: DEFINE expansion, keyword check, or plain IDENT.
 * Called from both {ALPHA}{ALNUM}* and {DIGIT}+{ALPHA}{ALNUM}* rules.
 *
 * If a DEFINE match is found, stores the expansion text in *expand_out
 * and returns 0. The caller (flex rule action) must unput() the expansion.
 * Otherwise returns the token type (IDENT, KW_FIRST, etc.).
 */
static const char *pending_expansion = NULL;

static int handle_identifier(void) {
    if (yyleng > 99) {
        SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
        diag_error(loc, "Token buffer overflow");
    }

    char *upper = strupper(strdup(yytext));
    const char *def_value = preproc_lookup_define(upper);

    if (def_value) {
        if (preproc_is_expanding(upper)) {
            SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
            diag_error(loc, "Circular DEFINE expansion: %s", upper);
            yylval.sval = upper;
            return IDENT;
        }

        if (g_preproc_events) {
            PreprocDefineInfo dinfo;
            if (preproc_lookup_define_info(upper, &dinfo)) {
                preproc_event_add_define_ref(g_preproc_events,
                    current_filename, yylloc.first_line, yylloc.first_column,
                    yylloc.first_column + yyleng - 1,
                    upper, dinfo.value, dinfo.filename, dinfo.line, dinfo.column);
            }
        }

        preproc_push_expansion(upper);
        free(upper);

        /* Signal caller to unput the expansion text */
        pending_expansion = def_value;
        return 0;
    } else {
        if (strcasecmp(upper, "FIRST") == 0) { free(upper); return KW_FIRST; }
        if (strcasecmp(upper, "NEXT") == 0)  { free(upper); return KW_NEXT; }
        if (strcasecmp(upper, "BACK") == 0)  { free(upper); return KW_BACK; }
        if (strcasecmp(upper, "LAST") == 0)  { free(upper); return KW_LAST; }
        yylval.ident_pair.canonical = upper;
        yylval.ident_pair.original = strdup(yytext);
        return IDENT;
    }
}

/*
 * Macro to call handle_identifier() and perform unput() if DEFINE expansion
 * is needed. Must be used inside a flex rule action (where unput is available).
 */
#define HANDLE_IDENT() do { \
    int tok = handle_identifier(); \
    if (tok) return tok; \
    /* DEFINE expansion: push text back into input */ \
    const char *exp = pending_expansion; \
    pending_expansion = NULL; \
    size_t len = strlen(exp); \
    for (int _i = (int)len - 1; _i >= 0; _i--) \
        unput(exp[_i]); \
} while(0)

/* Override default yylex declaration to create a wrapper */
#define YY_DECL int yylex_impl(void)

#line 1214 "lexer/lex.yy.c"
#define YY_NO_INPUT 1

#line 1217 "lexer/lex.yy.c"

#define INITIAL 0
#define COPY_STATE 1
#define COPY_SEMI 2
#define DEFINE_NAME 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 340 "lexer/tbol.l"


#line 1440 "lexer/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 497 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1182 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 342 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_PROGRAM; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 343 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_DATA; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 344 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); BEGIN(DEFINE_NAME); return KW_DEFINE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 345 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_PROC; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 346 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_END_PROC; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 347 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); copy_start_line = yylloc.first_line; copy_start_col = yylloc.first_column; BEGIN(COPY_STATE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 348 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_IF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 349 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_THEN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 350 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_ELSE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 351 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_DO; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 352 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_END; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 353 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_WHILE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 354 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_GOTO; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 355 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_GOTO_DEPENDING_ON; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 356 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_EXIT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 357 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_RETURN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 358 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_MOVE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 359 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_ABS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 360 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SWAP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 361 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_FILL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 362 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_CLEAR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 363 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_PUSH; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 364 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_POP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 365 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_STRING; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 366 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SUBSTR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 367 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_INSTR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 368 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_UPPERCASE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 369 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_LENGTH; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 370 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_EDIT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 371 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_ADD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 372 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SUBTRACT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 373 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_MULTIPLY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 374 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_DIVIDE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 375 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_AND; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 376 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_OR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 377 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_XOR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 378 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_TEST; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 379 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_NAVIGATE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 380 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_FETCH; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 381 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_OPEN_WINDOW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 382 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_CLOSE_WINDOW; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 383 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_OPEN_ERROR_WINDOW; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 384 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_KILL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 385 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_LINK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 386 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_TRANSFER; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 387 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_PURGE_CACHE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 388 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_OPEN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 389 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_CLOSE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 390 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_READ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 391 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_WRITE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 392 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_NOTE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 393 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_POINT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 394 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_DELETE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 395 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_CONNECT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 396 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_DISCONNECT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 397 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SEND; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 398 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_TIMEOUT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 399 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_PRIORITY; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 400 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_OPT_HDRS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 401 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_RECEIVE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 402 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_CANCEL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 403 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SAVE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 404 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_RESTORE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 405 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_RELEASE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 406 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_WAIT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 407 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_START; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 408 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_STOP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 409 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_REFRESH; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 410 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_ERASE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 411 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SET_CURSOR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 412 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SOUND; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 413 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_DEFINE_FIELD; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 414 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SET_ATTRIBUTE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 415 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SET_FUNCTION; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 416 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SET_KEY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 417 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_FORMAT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 418 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_MAKE_FORMAT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 419 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_LOOKUP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 420 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_SORT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 421 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_ERROR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 422 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return KW_TRIGGER_FUNCTION; }
	YY_BREAK
/* COPY_STATE: handle filename after COPY keyword */
case 82:
YY_RULE_SETUP
#line 425 "lexer/tbol.l"
{ current_column += yyleng; }
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 426 "lexer/tbol.l"
{ NEWLINE(); }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 427 "lexer/tbol.l"
{
    /* Comment in COPY state - skip */
    for (int i = 0; yytext[i]; i++) {
        if (yytext[i] == '\n') NEWLINE();
        else current_column++;
    }
}
	YY_BREAK
case 85:
#line 435 "lexer/tbol.l"
case 86:
YY_RULE_SETUP
#line 435 "lexer/tbol.l"
{
    UPDATE_LOC();
    /* Save filename, then wait for semicolon before pushing file */
    copy_filename = strupper(strdup(yytext));
    BEGIN(COPY_SEMI);
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 441 "lexer/tbol.l"
{
    UPDATE_LOC();
    SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
    diag_error(loc, "expected filename after COPY");
    BEGIN(INITIAL);
    yyless(0);
}
	YY_BREAK
/* COPY_SEMI: consume semicolon, then push file */
case 88:
YY_RULE_SETUP
#line 450 "lexer/tbol.l"
{ current_column += yyleng; }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 451 "lexer/tbol.l"
{ NEWLINE(); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 452 "lexer/tbol.l"
{
    UPDATE_LOC();
    /* Save current filename before push changes it to the COPY file */
    char *saved_filename = current_filename ? strdup(current_filename) : NULL;
    /* Now push the file - semicolon consumed from current buffer */
    if (preproc_push_file(copy_filename) == 0) {
        /* Record event for LSP */
        if (g_preproc_events) {
            int end_col = copy_start_col + 4 + 1 + (int)strlen(copy_filename);
            preproc_event_add_copy(g_preproc_events,
                saved_filename, copy_start_line, copy_start_col, end_col,
                copy_filename, preproc_get_last_resolved_path());
        }
    }
    free(saved_filename);
    free(copy_filename);
    copy_filename = NULL;
    BEGIN(INITIAL);
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 471 "lexer/tbol.l"
{
    UPDATE_LOC();
    SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
    diag_error(loc, "expected ';' after COPY filename");
    free(copy_filename);
    copy_filename = NULL;
    BEGIN(INITIAL);
    yyless(0);
}
	YY_BREAK
/* DEFINE_NAME: parse identifier without DEFINE expansion */
case 92:
YY_RULE_SETUP
#line 482 "lexer/tbol.l"
{ current_column += yyleng; SAVE_TEXT(); }
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 483 "lexer/tbol.l"
{ NEWLINE(); }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 484 "lexer/tbol.l"
{
    /* Comment in DEFINE_NAME state - skip */
    for (int i = 0; yytext[i]; i++) {
        if (yytext[i] == '\n') NEWLINE();
        else current_column++;
    }
}
	YY_BREAK
case 95:
#line 492 "lexer/tbol.l"
case 96:
YY_RULE_SETUP
#line 492 "lexer/tbol.l"
{
    UPDATE_LOC(); SAVE_TEXT();
    /* Return as plain IDENT without DEFINE expansion */
    yylval.ident_pair.canonical = strupper(strdup(yytext));
    yylval.ident_pair.original = strdup(yytext);
    BEGIN(INITIAL);
    return IDENT;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 500 "lexer/tbol.l"
{
    UPDATE_LOC();
    SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
    diag_error(loc, "expected identifier after DEFINE");
    BEGIN(INITIAL);
    yyless(0);
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 508 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return OP_NE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 509 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return OP_LE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 510 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return OP_GE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 511 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return OP_EQ; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 512 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return OP_LT; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 513 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return OP_GT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 515 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.ival = yytext[1] - '0'; return REG_I; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 516 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.ival = yytext[1] - '0'; return REG_D; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 517 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.ival = yytext[1] - '0'; return REG_P; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 519 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.ival = atoi(yytext + 1); return PEV; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 520 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.ival = atoi(yytext + 1); return GEV; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 522 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.ival = 0; return RDA_SLOT; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 523 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.ival = 221; return RDA_SLOT; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 525 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.sval = strdup(yytext); return LIT_HEX; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 526 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.sval = strdup(yytext); return LIT_NUM; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 527 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.sval = strdup(yytext); return LIT_NUM; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 528 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.sval = strdup(yytext); return LIT_NUM; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 529 "lexer/tbol.l"
{
    /* Digit-prefixed identifier (e.g., 6100DATA, 6100INIT) */
    UPDATE_LOC(); SAVE_TEXT();
    HANDLE_IDENT();
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 534 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.sval = strdup(yytext); return LIT_NUM; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 536 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); yylval.sval = process_string(yytext); return LIT_STR; }
	YY_BREAK
case 118:
/* rule 118 can match eol */
YY_RULE_SETUP
#line 538 "lexer/tbol.l"
{
    UPDATE_LOC();
    SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
    diag_error(loc, "unterminated string literal");
    NEWLINE();
    yylval.sval = strdup("");
    return LIT_STR;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 547 "lexer/tbol.l"
{
    UPDATE_LOC(); SAVE_TEXT();
    HANDLE_IDENT();
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 552 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return ';'; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 553 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return ','; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 554 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return '('; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 555 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return ')'; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 556 "lexer/tbol.l"
{ UPDATE_LOC(); SAVE_TEXT(); return ':'; }
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
#line 558 "lexer/tbol.l"
{
    for (int i = 0; yytext[i]; i++) {
        if (yytext[i] == '\n') {
            NEWLINE();
        } else {
            current_column++;
        }
    }
}
	YY_BREAK
case 126:
/* rule 126 can match eol */
YY_RULE_SETUP
#line 568 "lexer/tbol.l"
{
    UPDATE_LOC();
    SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
    diag_error(loc, "unterminated comment");
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 574 "lexer/tbol.l"
{ current_column += yyleng; SAVE_TEXT(); }
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 575 "lexer/tbol.l"
{ NEWLINE(); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 577 "lexer/tbol.l"
{
    UPDATE_LOC();
    SourceLoc loc = {current_filename, yylloc.first_line, yylloc.first_column};
    diag_error(loc, "invalid character '%c' (0x%02x)", yytext[0], (unsigned char)yytext[0]);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COPY_STATE):
case YY_STATE_EOF(COPY_SEMI):
case YY_STATE_EOF(DEFINE_NAME):
#line 583 "lexer/tbol.l"
{
    /* Try to pop include stack */
    if (preproc_pop_file()) {
        /* Switched to previous file - continue lexing from there */
        /* With yypop_buffer_state(), flex will continue from previous buffer */
    } else {
        /* No more files, end of input */
        yyterminate();
    }
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 594 "lexer/tbol.l"
ECHO;
	YY_BREAK
#line 2261 "lexer/lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 497 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 497 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 496);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 594 "lexer/tbol.l"


/*
 * Wrapper for yylex that clears DEFINE expansion tracking after each token.
 * This ensures cycle detection works correctly within a single token,
 * but resets between tokens.
 */
int yylex(void) {
    int token = yylex_impl();
    preproc_clear_expansions();
    return token;
}

